### ISSUE TITLE
Firefox shortcut conflict

### ISSUE THREAD

**Issue by Bogay** [uier/hackbar#9]
Because <kbd>Ctrl</kbd> / <kbd>Cmd</kbd> + <kbd>K</kbd> is a default shortcut for firefox.  
Users might not open hackbar use this shortcut. Add a method to customize shortcut might be helpful.

**Comment by uier** [comment]
kbar has released related feature, we only have to provide the input for user to choose their prefer hotkey
https://github.com/timc1/kbar/releases/tag/v0.1.0-beta.31
